# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artiste', '0004_auto_20170303_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='url_oeuvre',
            field=models.ImageField(height_field='url_height', upload_to='/static/artiste/static/img/', width_field='url_width'),
        ),
    ]
