# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artiste', '0005_auto_20170306_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='url_oeuvre',
            field=models.ImageField(upload_to='/static/artiste/static/img/'),
        ),
    ]
